### ISSUE TITLE
Option to use each joycon as a full controller?

### ISSUE THREAD

**Issue by glaita** [sam0x17/XJoy#12]
It would be really usefull if they joycons could be used individually (at least on some games). Is there a way to map de main buttons (axis, triggers and the 4 buttons) to it's xbox counterparts and use 2 joycons as 2 "full"(no really full) xbox controllers?

**Comment by sam0x17** [comment]
this will be possible when I add configuration file support, allowing you to completely customize the key-mappings. In the mean time it is possible to do what you want by customizing the mappings directly in the source code which you may or may not be able to do
