### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DylanHanna** [sam0x17/XJoy#13]
Everytime I attempt to open the XJoy.exe I get an application error that reads "The application was unable to start correctly (0xc000007b). How do I fix this? Before this occurred it said I was missing msvcp140.dll and vcruntime140.dll although I had both of them installed so I put the before mentioned dlls into the folder where XJoy.exe resides and got the application error. 
<img width="295" alt="error" src="https://user-images.githubusercontent.com/44147765/46923642-a8161700-cfcf-11e8-8681-7c29711e4130.PNG">
<img width="497" alt="folder" src="https://user-images.githubusercontent.com/44147765/46923643-a8aead80-cfcf-11e8-99c1-20a17e6fe30d.PNG">

**Comment by DylanHanna** [comment]
While testing I also made sure that the joycons were both "connected"

**Comment by sam0x17** [comment]
@DylanHanna any updates on this? Did you try any of the above?

**Comment by Yggromath** [comment]
Same problem here, I followed every step, what should I do?

**Comment by sam0x17** [comment]
@Yggromath I will look into this this weekend

**Comment by Yggromath** [comment]
thanks dude

**Comment by sam0x17** [comment]
@Yggromath so to confirm, you 1) installed the Install the ViGEm Bus Driver, 2) installed Visual C++ Redistributable for Visual Studio 2017 and 3) you have Windows 10?

**Comment by Yggromath** [comment]
Yep

**Comment by Isiolith** [comment]
Hello, I got a similar issue with the message "ucrtbased.dll" and then "vcruntime140d.dll" not found.
Maybe your binary is looking for debug dlls, whereas VisualC++redist only give us the non-debug version ?
Also these 2 dlls seems to be linked to 2015 redist, whereas 2017 redist is asked in the readme.

**Comment by Isiolith** [comment]
I got it working by adding "ucrtbased.dll" and "vcruntime140d.dll" in the XJoy folder

**Comment by sam0x17** [comment]
@Yggromath could you try also installing the 2015 redist, and we'll see if that fixes your issue? https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by FlaminSarge** [comment]
I'm also getting this issue, seems like it's trying to use the debug dll's for ucrtbase and vcruntime140 instead of the release ones.

**Comment by sam0x17** [comment]
Does anyone know what might cause this? I'm building everything in release mode

**Comment by bananakenobi** [comment]
same problem here, meh

**Comment by bananakenobi** [comment]
is there any solution?

**Comment by sam0x17** [comment]
Until someone or me can figure out why a dependency is using debug dlls even when I specify release for everything, the solution is to have visual studio 2017 installed on your machine (it's free)

**Comment by bananakenobi** [comment]
yea , its already installed , still not working

сб, 15 дек. 2018 г., 20:32 Sam Johnson notifications@github.com:

**Comment by FlaminSarge** [comment]
As a workaround for these issues on v0.1.5, grab v0.1.4 and copy urctbased.dll and vcruntime140d.dll into the same folder as XJoy.exe.

@DylanHanna can you rename this GitHub issue to "Application attempts to use missing/debug dlls" or something?

**Comment by sam0x17** [comment]
I'll just cut another release with those dlls in place again if that is working for people. It's not the proper way to fix this but its much easier than chasing this down.

**Comment by sam0x17** [comment]
OK I have re-uploaded the zip for 0.1.5 with the old dlls that were included with 0.1.4, so people should no longer experience this issue. If anyone wants to fix this properly I'd really appreciate it as I do not have any time to devote to this right now.
