### ISSUE TITLE
Setting the LEDs

### ISSUE THREAD

**Issue by Inari-Whitebear** [sam0x17/XJoy#17]
Probably not a top priority or anything, but I'd find it nice if this Program set the LEDs of the Joycons once connected, instead of letting them continue cycling them.

**Comment by sam0x17** [comment]
Yes, this is a low priority to-do item. Pull requests are welcome if anyone already knows how to do this.

**Comment by takashi1kun** [comment]
Yes this could be great, is quite anoying to see the leds cycling, you may take a look to this https://github.com/mfosse/JoyCon-Driver that thing is a similar thing to this and is capable of stopping the cycling and set the leds to one position.

**Comment by sam0x17** [comment]
Yes, I've looked extensively through that code, though I don't quite understand the initialization sequence, but anyone is free to submit a pull request ;)

**Comment by TideSinger** [comment]
`printf("setting LEDs...\n");
	for (int r = 0; r < 5; ++r) {
		for (int i = 0; i < joycons.size(); ++i) {
			Joycon *jc = &joycons[i];
			// Player LED Enable
			memset(buf, 0x00, 0x40);
			if (i == 0) {
				buf[0] = 0x0 | 0x0 | 0x0 | 0x1;		// solid 1
			}
			if (i == 1) {
				if (settings.combineJoyCons) {
					buf[0] = 0x0 | 0x0 | 0x0 | 0x1; // solid 1
				} else if (!settings.combineJoyCons) {
					buf[0] = 0x0 | 0x0 | 0x2 | 0x0; // solid 2
				}
			}
			//buf[0] = 0x80 | 0x40 | 0x2 | 0x1; // Flash top two, solid bottom two
			//buf[0] = 0x8 | 0x4 | 0x2 | 0x1; // All solid
			//buf[0] = 0x80 | 0x40 | 0x20 | 0x10; // All flashing
			//buf[0] = 0x80 | 0x00 | 0x20 | 0x10; // All flashing except 3rd light (off)
			jc->send_subcommand(0x01, 0x30, buf, 1);
		}`
This appears to be the code associated with it, it should be simple to set the lights based off of this code, just use the mem codes and send them to the controllers

**Comment by PeterHindes** [comment]
> `printf("setting LEDs...\n"); for (int r = 0; r < 5; ++r) { for (int i = 0; i < joycons.size(); ++i) { Joycon *jc = &joycons[i]; // Player LED Enable memset(buf, 0x00, 0x40); if (i == 0) { buf[0] = 0x0 | 0x0 | 0x0 | 0x1;	// solid 1 } if (i == 1) { if (settings.combineJoyCons) { buf[0] = 0x0 | 0x0 | 0x0 | 0x1; // solid 1 } else if (!settings.combineJoyCons) { buf[0] = 0x0 | 0x0 | 0x2 | 0x0; // solid 2 } } //buf[0] = 0x80 | 0x40 | 0x2 | 0x1; // Flash top two, solid bottom two //buf[0] = 0x8 | 0x4 | 0x2 | 0x1; // All solid //buf[0] = 0x80 | 0x40 | 0x20 | 0x10; // All flashing //buf[0] = 0x80 | 0x00 | 0x20 | 0x10; // All flashing except 3rd light (off) jc->send_subcommand(0x01, 0x30, buf, 1); }`
> This appears to be the code associated with it, it should be simple to set the lights based off of this code, just use the mem codes and send them to the controllers

make a pull request?

**Comment by sam0x17** [comment]
yes, I plan to include that in the next release -- was hoping TOML support would also be done in time, but if another week goes by I'll just cut a release now

**Comment by sam0x17** [comment]
here is prettified format of above code FYI:
```C++
printf("setting LEDs...\n");
for (int r = 0; r < 5;
  ++r) {
  for (int i = 0; i < joycons.size();
    ++i) {
    Joycon * jc = & joycons[i];
    // Player LED Enable memset(buf, 0x00, 0x40);
    if (i == 0) {
      buf[0] = 0x0 | 0x0 | 0x0 | 0x1;
      // solid 1 } if (i == 1) { if (settings.combineJoyCons) { buf[0] = 0x0 | 0x0 | 0x0 | 0x1;
      // solid 1 } else if (!settings.combineJoyCons) { buf[0] = 0x0 | 0x0 | 0x2 | 0x0;
      // solid 2 } } //buf[0] = 0x80 | 0x40 | 0x2 | 0x1;
      // Flash top two, solid bottom two //buf[0] = 0x8 | 0x4 | 0x2 | 0x1;
      // All solid //buf[0] = 0x80 | 0x40 | 0x20 | 0x10;
      // All flashing //buf[0] = 0x80 | 0x00 | 0x20 | 0x10;
      // All flashing except 3rd light (off) jc->send_subcommand(0x01, 0x30, buf, 1);
    }
```
