### ISSUE TITLE
Error in program

### ISSUE THREAD

**Issue by JovannMC** [sam0x17/XJoy#18]
When I open xJoy.exe with the Nintendo Switch Joy Cons connected, it says:

XJoy v0.1.5

initializing emulated Xbox 360 controller...
connection error: bus not found
press [ENTER] to exit

![image](https://user-images.githubusercontent.com/45893380/50040979-1aea4f80-005e-11e9-9af4-32aba017cc75.png)

**Comment by sam0x17** [comment]
This probably means you did not install the ViGem bus. See the installation instructions.
