### ISSUE TITLE
How to Customize

### ISSUE THREAD

**Issue by UsernameK1** [sam0x17/XJoy#20]
I'm having trouble learning how to customize the button inputs and would like to know how?

**Comment by sam0x17** [comment]
Right now there is no way other than modifying the code and compiling yourself. If I ever get around to it I plan to add a config file to customize the bindings. The default bindings can be changed in XJoy.cpp in the `process_buttons` method: https://github.com/sam0x17/XJoy/blob/master/XJoy/XJoy.cpp#L237
