### ISSUE TITLE
"could not find __ Joy-Con"

### ISSUE THREAD

**Issue by kjholt** [sam0x17/XJoy#23]
Not sure what I did wrong but when I get to the finding-Joy-Cons step, XJoy says "could not find left Joy-Con" (or right Joy-Con, depending). Both are connected/paired to Windows as "Joy-Con (L)" and "Joy-Con (R)" under "Mouse, keyboard, & pen."

Note a possible complicating factor: I'm running Windows on a Mac via KB Parallels virtual machine. I might be overlooking something as I'm not great with Windows.

Thanks.

**Comment by sam0x17** [comment]
That might be the source of your trouble. I would verify first that bluetooth devices work properly in Parallels (as in pair something like a keyboard or xbox controller and see if you can actually _use_ it, not just pair it). My husband actually uses this same setup so I could try debugging if nothing else works.

**Comment by sam0x17** [comment]
It could be that they are coming in with a different product id. Is there a way you can check that?

**Comment by sam0x17** [comment]
My guess is this is a parallels specific issue. I don't have a mac, so I can't investigate any further.
