### ISSUE TITLE
Input config.

### ISSUE THREAD

**Issue by Rexord0** [sam0x17/XJoy#25]
Look i know u dont have time, but can u please change the input of the buttons to be like the xbox controller like x=Y and B=a pls

i will do it myself but i dont know how :(

**Comment by sam0x17** [comment]
fixed -- that should have been the default anyway

y'all need to learn C++

**Comment by Rexord0** [comment]
Tanks, I need too, Tho I only know the Basics ☹

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
