### ISSUE TITLE
XJoy doesn't detect joy-cons

### ISSUE THREAD

**Issue by Shinwoir** [sam0x17/XJoy#26]
It worked perfectly before, but now they aren't detected anymore
I have tried various other methods and Xjoy was the most efficient, but for whatever reason it doesn't detect anything
All dependencies are installed.

**Comment by sam0x17** [comment]
@Shinwoir could you try a few of the older versions and see at what version release it stopped working for you? Otherwise I have no way of debugging this. Also I would definitely try re-pairing the Joycons with your PC -- sometimes they just need to pair again.

**Comment by sam0x17** [comment]
any updates on this @Shinwoir ?

**Comment by sam0x17** [comment]
I'm going to archive this unless @Shinwoir follows up as no one else has been having this issue and we've done new releases since then
