### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by deltaFigure** [sam0x17/XJoy#29]
Hi, when i'm using the latest version (0.1.8) i get the error that i'm missing the dll: VCRUNTIME140D.dll
Using an older version (0.1.4) works fine.

**Comment by greysdawn** [comment]
I just had to fix this issue by copying the dlls rom 0.1.4/0.1.5 into the folder with 0.1.8 and that worked
Going by an old, closed issue, it's a dependency that's causing the problem by looking for debug dlls that it shouldn't need, so I guess the best way to fix it is either by copying the dlls or using an older version like you are now

**Comment by sam0x17** [comment]
haha ok I've given up trying to get this to not need those dll's so I'm
just going to cut a version that includes them by default with the next
release

**Comment by greysdawn** [comment]
@sam0x17 Honestly I don't blame you, and as long as it fixes the issue I'm sure most people won't mind (I know I don't, personally)

**Comment by sam0x17** [comment]
I have re-released the current release to include the missing dll files, so it should now work on anyone's machine.
