### ISSUE TITLE
All buttons pressed at all times.

### ISSUE THREAD

**Issue by anonymus177** [sam0x17/XJoy#32]
The title is self-explanatory, when I start the program all the buttons are being pressed so nothing is playable.  Log looks like this and it just keeps going and going. What am I doing wrong?
![Bez názvu](https://user-images.githubusercontent.com/28503821/60684007-99dc9380-9e9b-11e9-8456-f7daf0105c31.jpg)

EDIT: I tried both the older and newer versions, 0.14, 0.15, 0.17 and 0.18.

**Comment by sam0x17** [comment]
@anonymus177 do you happen to have any other controller emulators installed? I am thinking there might be some other software interfering with XJoy. The best way to find out would be to try installing on a fresh install of windows 10 and see if it works. Please let me know anything unique about your setup that you think could be causing this, as without the ability to reproduce the error I have no way to debug.

**Comment by anonymus177** [comment]
Xjoy was the first I tried, I started trying the others only after it didn't work. But amazing news - after the last update it miraculously works! So it could have been caused by the analog sticks maybe? I have calibrated them by myself, maybe that was the issue, but now it all works as it should and I'd like to thank you for your amazing work!

**Comment by sam0x17** [comment]
Hah great to hear its working and yeah no idea why lol!
