### ISSUE TITLE
user cal not found

### ISSUE THREAD

**Issue by Sicurious** [sam0x17/XJoy#33]
for me it keeps saying "user cal not found". what can i do about that error? i followed all the instructions and can't seem to make it work.

**Comment by sam0x17** [comment]
Looks like this error was added with the new full analog support changes by @wormyrocks
https://github.com/sam0x17/XJoy/blob/master/XJoy/XJoy.cpp#L316 so he might be able to offer some insight. Is the error message showing just once, twice, in a loop? Also, have you tried seeing if XJoy is working anyway despite the error?

**Comment by Sicurious** [comment]
the error pops up twice. The first one after the left joycon is found and the second one after the right one is found. And for me it shows the button that is being pressed but it doesnt seem to do anything. Like when i try to use it ingame it doesnt work at all :-/

**Comment by wormyrocks** [comment]
Hi,

"User cal not found" displays when the user has not done manual analog stick calibration on the Switch, in which case the program falls back to using the factory stick calibration.

Doing the user calibration may be helpful if you have the Joy-Con drift issue.

So short answer, you can safely ignore the "user cal not found" message.

**Comment by Gloix** [comment]
May I suggest using the word "calibration" instead of "cal" as I kept seeing this issue and thinking "Why would XJoy care about some freaking calendar".

**Comment by sam0x17** [comment]
@Gloix yes I was a bit confused by this as well when I saw it -- I will change the text

It also sounds like you have a separate issue where XJoy isn't working for you? What game are you trying to use it with. Remember that the game needs to support Xbox 360 controller input. For some games, you need to select the controller or enable controller mode under input/control options.

**Comment by sam0x17** [comment]
note: ambigious error message has been fixed with db502cb7846600e3d9e6eb7b130a9938f414c121

**Comment by Gloix** [comment]
I may have not written that well. I don't have this issue. I just saw it in the issues section of the repo and though of "calendar" as a word for "cal". 🙃

**Comment by sam0x17** [comment]
ah ok excellent -- closing!

**Comment by svbeon** [comment]
So the calibration should be done on a switch! Might want to add a more descriptive message for this, I kept looking for a way to open XJoy in some form of calibration mode...

**Comment by sam0x17** [comment]
ah ok, thanks for the context @svbeon I did not realize that. Does the calibration only pertain to gyroscope or also other things like analog controls?

**Comment by svbeon** [comment]
No idea tbqh. I can try looking into it later
