### ISSUE TITLE
unable to find XJoy.cpp

### ISSUE THREAD

**Issue by NexusTheBrony** [sam0x17/XJoy#36]
So I downloaded XJoy and I want to fix the controls to where a is a, etc. but i can't find XJoy.cpp.

![files](https://user-images.githubusercontent.com/32724830/62824275-73c8a400-bb69-11e9-91fa-8bc5ed28189c.png)
these are all the files I have. How would I change the controls? If I can't change the controls without building the program, would x360ce be able to do it?

**Comment by sam0x17** [comment]
You will need to:

1. Install visual studio
2. Install git
3. Clone the repo
4. Open the solution / .sln file in the root of the repo with visual studio
5. Make changes to XJoy.cpp to use the control scheme you want
6. Rebuild the project in visual studio
7. Browse to where the visual studio project is located, find the .exe file that got built, and overwrite your usual XJoy.exe with that

Once we have configuration file support, you won’t have to do any of this, but the person working on it stopped and I haven’t had time to add it.

-Sam
