### ISSUE TITLE
Issue with XJoy and DLL files

### ISSUE THREAD

**Issue by JDCSG** [sam0x17/XJoy#40]
Specifically MSVP140.dll

**Comment by sam0x17** [comment]
This happens when you are missing a Visual C++ Redistributable https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by JDCSG** [comment]
Okay, it's working and I'm scared.

**Comment by JDCSG** [comment]
nvm still not working

**Comment by JDCSG** [comment]
I've seen people drag and drop those files in the XJoy folder, but I'm pretty sure that won't work.

**Comment by sam0x17** [comment]
Next step would be to try installing Visual Studio 2019 Community. For some reason some people need to have this installed.

**Comment by Sekorts** [comment]
Hi! i'm haivng the same issue, I'm on windows 10, I installed both the vgem driver and visual studios from 2015 to 2019 and I still get the same error message, even when the files are on the same folder as the xjoy.exe. Any ideas?
