### ISSUE TITLE
XJoy not reading analog stick controls

### ISSUE THREAD

**Issue by raindew120** [sam0x17/XJoy#41]
Is the software not supposed to be able to pick up the analog stick controls? Everything works fine except the left and right analog sticks. It doesn't even show up in the command lines in XJoy.exe when I try moving them. I've tried it on both my Windows 8.1 and my Windows 10 laptops, and neither works.

I'm on XJoy v0.2.0.

**Comment by raindew120** [comment]
Update: Oops nevermind, doesn't seem like it was XJoy's fault after all. Though the analog inputs don't show up in the command prompt, they work perfectly fine in games that support Xbox contollers, like Stardew Valley. I was having problems getting Retroarch to recognise the analog stick inputs, and it seems like it's an issue with RetroArch rather than XJoy.

**Comment by sam0x17** [comment]
Yeah, I had it suppress printing the analog state in the terminal because it bogged down performance a ton

Glad it works!!
