### ISSUE TITLE
initializing emulated Xbox 360 controller... connection error: bus not found

### ISSUE THREAD

**Issue by RiskFX** [sam0x17/XJoy#45]
I installed everything that was required for this to work. So when I run XJoy.exe I get this:

XJoy v0.2.0

initializing emulated Xbox 360 controller...
connection error: bus not found
press [ENTER] to exit

**Comment by sam0x17** [comment]
This usually indicates you don't have ViGEm installed or installed properly. Please ensure that you have followed the setup instructions on the main page

**Comment by super-shooter** [comment]
i downloaded and installed the ViGEm and had the same problem, do i need to copy and paste the ViGEm somewhere?

**Comment by sam0x17** [comment]
you might want to try an older version, it's possible ViGEm has been updated to where it is incompatible with XJoy. If so please let us know here so I can update the README

**Comment by RiskFX** [comment]
it's still not working, i'm getting the same error on my laptop

**Comment by sam0x17** [comment]
I don't have a windows machine at the moment to investigate this but hopefully someone from the community will.

**Comment by RiskFX** [comment]
I found the issue! Installing the drivers doesn't work until you go through the ViGEm Bus Setup, then it will work.

**Comment by sam0x17** [comment]
yay community :100:  :tada:
