### ISSUE TITLE
i only have left joycon

### ISSUE THREAD

**Issue by upwn** [sam0x17/XJoy#49]
Hi, I want to be able to just use the left joycon as an xbox controller, but when I start up xjoy is detects the left controller, doesn't detect the right controller, and then tells me to hit enter to quit the program. I was hoping to do some PC gaming on steam using the left joycon as my WASD plus other functions that i'd be able to map in through steam, and then a mouse for aiming.  but i didn't realize that i'd need both joycons if that's the case. an Xbox controller does seem to appear in my device list on steam, but the joy con won't do anything still. There's also no virtual controller appearing like the readme file suggests.

**Comment by upwn** [comment]
ok now i'm playing with visual studio like a noob. I read that you said you can disable a controller by commenting out the relevant line in visual studio. Do I disable all lines that mention the right joycon, or just line 519 like was highlighted in the previous comment? and how do i comment it out, am i just deleting it from the document? any help would be appreciated

**Comment by upwn** [comment]
or if you could mention what i need to do with YAML or TOML (completely new to both of those terms) to disable the need for the right switch controller

**Comment by sam0x17** [comment]
You'll just want to completely disable the code that initializes the joycon
you don't want. I think there are two functions near the bottom of the file
that do that.

**Comment by upwn** [comment]
thanks for your quick response! i read up on what commenting out was after i posted, then through trial and error I managed to comment out the the right thing (the function's that mention the right joy con initializing at 367, and also at 742) it told me to comment out some other stuff in relation and clean it up, and it worked! I thought it would be really difficult to use, but after i stared at it for long enough it began to make sense. Right now i'm remapping the L_DPAD_SL button to XUSB_GAMEPAD_B (instead of X) because this is the back button in steam big picture. You created some good code! Good job! Thanks!
