### ISSUE TITLE
warning: user calibration data not found

### ISSUE THREAD

**Issue by Nic17tm** [sam0x17/XJoy#51]
The joycons are connected to my pc using bluetooth, I follow all the steps and everything is good, 
but when I open xJoy it says 

warning: user calibration data not found
Only in 1 joycon

**Comment by codingForCats** [comment]
I also have this problem, although I wasn't able to install visual C++ for 2017, I think because I have a newer version

**Comment by Cyberblader** [comment]
This happens to me too on both Joy-Cons every time I open XJoy

**Comment by sam0x17** [comment]
Yeah this isn't an error, it's fine.
