### ISSUE TITLE
bus not found error

### ISSUE THREAD

**Issue by sriracha0** [sam0x17/XJoy#59]
I have been using Xjoy for as long as I can remember with no problem, but recently upon running Xjoy v0.2.0, I received an error reading "connection error: bus not found." After doing a little searching this seems to be referring to the ViGEmBus that's specified in the README, which I already had, and have downloaded and redownloaded at this point with no change. I've been using the program successfully for a long time and I can't pinpoint what caused it to stop working so suddenly. I'm not a programmer, and I need some help figuring out what went wrong.

I'm on Windows 10, let me know if you need more information about my specs. Thanks

**Comment by sam0x17** [comment]
Sorry this has happened --- I would definitely try running older versions
of ViGEm in case an update caused this (but if you didn't update it, it
probably isn't that) and/or an older version of XJoy. Let me know if that
helps!

**Comment by sriracha0** [comment]
After jumping through some more hoops regarding bluetooth drivers, your recommendation worked. Thank you!!!!!!
