### ISSUE TITLE
Unable to control anything, does connect

### ISSUE THREAD

**Issue by LuceCannon21** [sam0x17/XJoy#67]
I started having issues a few days ago, I use xjoy to play stardew valley as wasd controls hurt my wrist and I'm not as fast with them. When I tried to use Xjoy to control among us one night (I realized it wouldn't work early on, whoops), it just stopped connecting to the joycons I usually use. I tried to switch around what controllers I use, and its just not working. I disconnect them from my computer when I'm not using them, so its not something I think can be corrected by disconnecting and reconnecting. When I open xjoy with the connected controllers it says "User Calibration not found"

I really love xjoy and I want to be able to play games again, so anything that can be done to fix this would be really really nice. I'm sadly not a coder and I don't know how I would remedy this on my own.

**Comment by sam0x17** [comment]
User Calibration not found always gets said don't worry about that one

You probably have to unpair the old controllers from your windows settings > bluetooth devices
