### ISSUE TITLE
Support for only one joycon at a time.

### ISSUE THREAD

**Issue by atofigh** [sam0x17/XJoy#7]
I've tinkered with XJoy a bit, including the code and I love it. My main use case for connecting the switch joycon to my windows machine, is to use the left joycon for movement in game (instead of the wasd keys) and use mouse for aiming. Suggestion: Do not require the presence of both left and right controllers.

**Comment by sam0x17** [comment]
@atofigh great suggestion. I plan to add support for this with the introduction of config files, which I am working on. In the mean time feel free to comment out the relevant line to disable either controller https://github.com/sam0x17/XJoy/blob/master/XJoy/XJoy.cpp#L519

**Comment by sam0x17** [comment]
closing this in favor of #2, which will add support for this
