### ISSUE TITLE
Xjoy bus not found

### ISSUE THREAD

**Issue by qirmez** [sam0x17/XJoy#78]
I've been using Xjoy for a long time now w/o issues, yet today I wasn't able to connect. Getting: 'connection error: bus not found.'  I'm a total noob with this but with the few guides i've seen i installed a vigem bus driver and ran it, selected repair because the modify option wasn't working for me. I don't know what a vigem bus driver is, or how I'm supposed to proceed after this. 

Windows 10. Recently updated my BIOS firmware from Dell's site under driver's update, that's the only change I can think of prior to this error.

**Comment by sam0x17** [comment]
You might be able to try a more recent version of the bus potentially. It's also vaguely possible something like anti-virus etc tampered with it. I didn't make the bus so I can't really help very much other than pointing you to the vigem github / discord

**Comment by qirmez** [comment]
> You might be able to try a more recent version of the bus potentially. It's also vaguely possible something like anti-virus etc tampered with it. I didn't make the bus so I can't really help very much other than pointing you to the vigem github / discord, but I can confirm if it says "bus not found" there is something wrong with the vigem bus installation.

I ended up fixing it by deleting/uninstalling all files required for Xjoy, restarting and reinstalling all of them from scratch. Thanks anyway!
