### ISSUE TITLE
Support for the SL and SR buttons on the attachment rails

### ISSUE THREAD

**Issue by atofigh** [sam0x17/XJoy#8]
When using a single joycon, the SL and SR buttons are quite useful. I tinkered with the code a bit and it looks like there is distinct signals detected, just that the code is not set up to handle that type of input yet.

**Comment by sam0x17** [comment]
@atofigh yes I forgot to map these because my joycons have battery cases that cover them up! I will add this soon but top priority right now is adding full analog support.

**Comment by atofigh** [comment]
Analog support sounds like an awesome feature. And thanks for sharing the code.

Just FYI, the SL and SR buttons are mapped to the dpad region with values 32 and 64 respectively.

**Comment by atofigh** [comment]
Sorry, got that wrong. the values are 16 and 32.

**Comment by sam0x17** [comment]
@atofigh thanks this saves me some time!

**Comment by sam0x17** [comment]
@atofigh if I add this before we have config file support, what would you want those bound to by default?

**Comment by atofigh** [comment]
Personally, I bound them to A and B because I just need extra buttons when using the left joycon alone. But that doesn't seem like a very natural choice. I would suggest mapping them to either LT/RT or LB/RB.

**Comment by ziobbe** [comment]
If I understand this correctly the triggers on the xbox 360/xbox one controller are analog input so maybe it would be a nice idea to map them as full, mid and low pressure of the corresponding (l or r) trigger or full low pressure plus a nice redundant keypress.
