### ISSUE TITLE
i have made a single left controller fork, what do i do with it?

### ISSUE THREAD

**Issue by upwn** [sam0x17/XJoy#88]
i'm new to github sorry i just charge in and mess with things. I don't know how to properly give this back.

**Comment by nalor** [comment]
Hi! Just open your forked repo, open the "Settings" tab and scroll down into the "Danger zone" at the bottom. Click the "Delete this repository" button when you're really sure you don't need the forked repository any longer.

**Comment by upwn** [comment]
well, that is to say i didn't make a fork. I downloaded xjoy and edited it in visual studio to start up with just the left joycon so it could be used controller with mouse. I very rarely use github so i'm unfamiliar on where to upload it.

**Comment by sam0x17** [comment]
very short crash course in git ;) https://gist.github.com/brandon1024/14b5f9fcfd982658d01811ee3045ff1e
