### ISSUE TITLE
Support analog stick acceleration

### ISSUE THREAD

**Issue by HarryPeach** [sam0x17/XJoy#9]
When moving the analog sticks, the full force is registered rather than the appropriate amount based on how much the analog stick is pushed.

For example, in a game if the stick is pushed slightly the character walks slower than if it was pushed entirely. I have not been able to replicate this functionality in Xjoy.

Thanks for the great work, hope its possible to add this!

**Comment by sam0x17** [comment]
@HarryPeach thanks for reporting this yes this is known and I am working on adding full analog support. By default when you connect to a Joy-Con with no calibration/initialization, it will report back analog stick movements as if they were an 8-way DPAD. This is why movement is currently limited. I hope to have some time to work on this next week. Please follow #1 for progress on this issue.
