### ISSUE TITLE
connection error: bus not found

### ISSUE THREAD

**Issue by TF21045** [sam0x17/XJoy#91]
![image](https://user-images.githubusercontent.com/53613828/179177449-8ff1e105-7a85-4a1c-9548-0a5b22a48c1f.png)

No matter what I do, it doesn't work.
Ran as administrator, Run as user, using different versions, Nothing!

**Comment by A-Grant787** [comment]
Try running this. It should work after this.
https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.16.116

**Comment by TF21045** [comment]
aight nvm had to update windows from 1809 to 21H2
thanks for trying!
