### ISSUE TITLE
Left Analog Stick moving on its own when playing Kingdom Hearts 3 on PC

### ISSUE THREAD

**Issue by NaturalHarmonia** [sam0x17/XJoy#93]
Occasionally when I am playing Kingdom Hearts 3 the left analog stick will do its own thing and move on its own. This is especially noticeable on the pause screen as the left analog stick will move up and down every few seconds. For the most part I followed the installation instructions but during the part where I was supposed to install Visual C++ Redistributable for Visual Studio 2017 I got an error during installation because I have a later version of it installed on Windows 11. Should I specifically be using Visual C++ Redistributable for Visual Studio 2017 or is a later version sufficient? Perhaps that is what is causing the issue.

**Comment by sam0x17** [comment]
That's not what is causing the issue. When it first connets it calibrates the analog sticks so best thing to do is spin the sticks around in a full circle when you first connect, and that will usually prevent this. Certain joycons sometimes have more drift than others.

**Comment by NaturalHarmonia** [comment]
> That's not what is causing the issue. When it first connets it calibrates the analog sticks so best thing to do is spin the sticks around in a full circle when you first connect, and that will usually prevent this. Certain joycons sometimes have more drift than others.

I did that several times and I am still having the same issue. I wonder if anyone else has ever had this issue.
